export const projects = [
    {
        slug: "luxury-portfolio",
        title: "LUXURY PORTFOLIO",
        category: "Web Design",
        description: "A high-end portfolio website for a luxury brand, featuring smooth animations and premium typography.",
        challenge: "Creating a sense of exclusivity and premium feel while maintaining high performance and accessibility.",
        goal: "To showcase the brand's products in a way that feels immersive and expensive.",
        outcome: "A stunning website that increased brand perception and user engagement by 40%.",
        tools: ["Next.js", "GSAP", "TailwindCSS", "WebGL"],
        role: "Lead Developer & Designer",
        year: "2024",
        images: ["/placeholder-1.jpg", "/placeholder-detail-1.jpg", "/placeholder-detail-2.jpg"],
    },
    {
        slug: "f1-experience",
        title: "F1 EXPERIENCE",
        category: "Interactive",
        description: "An immersive 3D experience allowing users to explore an F1 car and track details.",
        challenge: "Optimizing 3D assets for web performance without sacrificing visual fidelity.",
        goal: "To bring the excitement of F1 racing to the web browser.",
        outcome: "An award-winning interactive site featured on Awwwards.",
        tools: ["Three.js", "React Three Fiber", "Blender", "Next.js"],
        role: "Creative Developer",
        year: "2023",
        images: ["/placeholder-2.jpg", "/placeholder-detail-3.jpg"],
    },
    {
        slug: "ai-assistant",
        title: "AI ASSISTANT",
        category: "Application",
        description: "A voice-activated AI assistant interface with real-time visualization.",
        challenge: "Integrating real-time audio processing with smooth visual feedback.",
        goal: "To create a futuristic and intuitive interface for AI interaction.",
        outcome: "A seamless voice interface that feels natural and responsive.",
        tools: ["Python", "React", "WebAudio API", "OpenAI"],
        role: "Full Stack Developer",
        year: "2024",
        images: ["/placeholder-3.jpg"],
    },
    {
        slug: "ecommerce-dashboard",
        title: "ECOMMERCE DASHBOARD",
        category: "Development",
        description: "A comprehensive analytics dashboard for e-commerce store owners.",
        challenge: "Visualizing complex data sets in a clean and understandable way.",
        goal: "To empower store owners with actionable insights.",
        outcome: "A highly customizable dashboard used by over 500 merchants.",
        tools: ["Next.js", "D3.js", "Supabase", "TailwindCSS"],
        role: "Frontend Engineer",
        year: "2023",
        images: ["/placeholder-4.jpg"],
    },
];
